title: H.I. Blog
author: H. Iijima

description: >-
  This is a my personal blog.
  There is no guarantee on information described.

# Use latest version of minima
remote_theme: jekyll/minima

# Use old version of minima on Github Pages
# theme: minima

header_pages:
  - about.md

show_excerpts: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima specific settings (Minima >= 3.0)
minima:
  # skin: [classic, dark, auto]
  skin: dark
  date_format: "%Y-%m-%d"
  social_links:
    - { platform: github,         user_url: "https://github.com/iijimahr" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=cFi3h5UAAAAJ" }
    # - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    # - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    # - { platform: x,              user_url: "https://x.com/jekyllrb" }
    # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
